-- =====================================================================
--  HOSTEL PORTAL — DATABASE SETUP
--  Paste this whole file into Supabase > SQL Editor and press "Run".
--  It is safe to run again later (it won't delete your data).
-- =====================================================================

-- ---------- 1. TABLES ----------

create table if not exists public.settings (
  id            int primary key default 1 check (id = 1),
  hostel_name   text not null default 'My Hostel',
  address       text,
  phone         text,
  currency      text not null default 'Rs.',
  country_code  text not null default '92',
  due_day       int  not null default 1 check (due_day between 1 and 28),
  invoice_note  text default 'Please pay by the due date. Thank you!',
  updated_at    timestamptz not null default now()
);
insert into public.settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text,
  email       text,
  role        text not null default 'staff' check (role in ('admin', 'staff')),
  approved    boolean not null default false,
  created_at  timestamptz not null default now()
);

create table if not exists public.flats (
  id            uuid primary key default gen_random_uuid(),
  flat_no       text not null unique,
  floor         text,
  flat_type     text,
  monthly_rent  numeric(12,2) not null default 0 check (monthly_rent >= 0),
  notes         text,
  created_at    timestamptz not null default now()
);

create table if not exists public.residents (
  id                 uuid primary key default gen_random_uuid(),
  full_name          text not null,
  phone              text,
  cnic               text,
  email              text,
  occupation         text,
  permanent_address  text,
  emergency_name     text,
  emergency_phone    text,
  persons            int not null default 1 check (persons >= 1),
  flat_id            uuid references public.flats (id) on delete set null,
  monthly_rent       numeric(12,2) not null default 0 check (monthly_rent >= 0),
  security_deposit   numeric(12,2) not null default 0 check (security_deposit >= 0),
  check_in           date not null default current_date,
  check_out          date,
  status             text not null default 'active' check (status in ('active', 'left')),
  notes              text,
  created_at         timestamptz not null default now()
);
-- A flat can only have one active resident at a time
create unique index if not exists one_active_resident_per_flat
  on public.residents (flat_id) where status = 'active';

create table if not exists public.charges (
  id           uuid primary key default gen_random_uuid(),
  resident_id  uuid not null references public.residents (id) on delete cascade,
  flat_id      uuid references public.flats (id) on delete set null,
  type         text not null check (type in ('rent', 'utilities', 'deposit', 'other')),
  description  text,
  amount       numeric(12,2) not null check (amount >= 0),
  period       date not null,                       -- always the 1st of the month
  due_date     date,
  created_by   uuid default auth.uid(),
  created_at   timestamptz not null default now()
);
create unique index if not exists one_rent_per_month
  on public.charges (resident_id, period) where type = 'rent';
create index if not exists charges_resident_idx on public.charges (resident_id);
create index if not exists charges_period_idx on public.charges (period);

create table if not exists public.payments (
  id           uuid primary key default gen_random_uuid(),
  receipt_no   bigint generated by default as identity unique,
  resident_id  uuid not null references public.residents (id) on delete cascade,
  amount       numeric(12,2) not null check (amount > 0),
  kind         text not null default 'payment' check (kind in ('payment', 'refund')),
  method       text not null default 'Cash',
  reference    text,
  paid_on      date not null default current_date,
  note         text,
  created_by   uuid default auth.uid(),
  created_at   timestamptz not null default now()
);
create index if not exists payments_resident_idx on public.payments (resident_id);
create index if not exists payments_date_idx on public.payments (paid_on);

create table if not exists public.invoices (
  id                uuid primary key default gen_random_uuid(),
  invoice_no        bigint generated by default as identity unique,
  resident_id       uuid not null references public.residents (id) on delete cascade,
  period            date not null,
  issue_date        date not null default current_date,
  due_date          date,
  previous_balance  numeric(12,2) not null default 0,
  current_charges   numeric(12,2) not null default 0,
  payments_in_month numeric(12,2) not null default 0,
  total_due         numeric(12,2) not null default 0,
  created_by        uuid default auth.uid(),
  created_at        timestamptz not null default now(),
  unique (resident_id, period)
);

create table if not exists public.activity_log (
  id          bigint generated by default as identity primary key,
  user_id     uuid,
  table_name  text not null,
  action      text not null,
  record_id   text,
  details     jsonb,
  created_at  timestamptz not null default now()
);
create index if not exists activity_created_idx on public.activity_log (created_at desc);

-- ---------- 2. HELPER FUNCTIONS ----------

create or replace function public.is_approved()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and approved);
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and approved and role = 'admin');
$$;

-- New sign-up => profile. The very first account becomes the approved admin.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  first_user boolean;
begin
  select not exists (select 1 from public.profiles) into first_user;
  insert into public.profiles (id, email, full_name, role, approved)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    case when first_user then 'admin' else 'staff' end,
    first_user
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Activity log: records who added / changed / deleted what
create or replace function public.log_activity()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  rec jsonb;
begin
  if tg_op = 'DELETE' then rec := to_jsonb(old); else rec := to_jsonb(new); end if;
  insert into public.activity_log (user_id, table_name, action, record_id, details)
  values (auth.uid(), tg_table_name, tg_op, rec ->> 'id', rec);
  return null;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array['flats','residents','charges','payments','invoices','settings','profiles'] loop
    execute format('drop trigger if exists log_%1$s on public.%1$I', t);
    execute format('create trigger log_%1$s after insert or update or delete on public.%1$I
                    for each row execute function public.log_activity()', t);
  end loop;
end $$;

-- Add rent for every active resident for a given month (skips anyone already charged)
create or replace function public.generate_monthly_rent(p_period date)
returns integer language plpgsql security invoker set search_path = public as $$
declare
  v_period date := date_trunc('month', p_period)::date;
  v_due_day int;
  v_count int;
begin
  if not public.is_approved() then
    raise exception 'Not allowed';
  end if;
  select due_day into v_due_day from public.settings where id = 1;

  insert into public.charges (resident_id, flat_id, type, description, amount, period, due_date)
  select r.id, r.flat_id, 'rent',
         'Rent - ' || to_char(v_period, 'FMMonth YYYY'),
         r.monthly_rent, v_period, v_period + (coalesce(v_due_day, 1) - 1)
  from public.residents r
  where r.status = 'active'
    and r.monthly_rent > 0
    and r.check_in <= (v_period + interval '1 month' - interval '1 day')::date
    and not exists (
      select 1 from public.charges c
      where c.resident_id = r.id and c.type = 'rent' and c.period = v_period
    );

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ---------- 3. VIEWS (balances are always calculated, never typed) ----------

drop view if exists public.residents_overview;
create view public.residents_overview with (security_invoker = true) as
select
  r.*,
  f.flat_no,
  f.floor,
  coalesce(c.total, 0)                                         as total_charges,
  coalesce(p.paid, 0)                                          as total_paid,
  coalesce(p.refunded, 0)                                      as total_refunded,
  coalesce(c.total, 0) - coalesce(p.paid, 0) + coalesce(p.refunded, 0) as balance,
  p.last_payment
from public.residents r
left join public.flats f on f.id = r.flat_id
left join (
  select resident_id, sum(amount) as total from public.charges group by resident_id
) c on c.resident_id = r.id
left join (
  select resident_id,
         sum(case when kind = 'payment' then amount else 0 end) as paid,
         sum(case when kind = 'refund'  then amount else 0 end) as refunded,
         max(case when kind = 'payment' then paid_on end)       as last_payment
  from public.payments group by resident_id
) p on p.resident_id = r.id;

drop view if exists public.flats_overview;
create view public.flats_overview with (security_invoker = true) as
select
  f.*,
  r.id        as resident_id,
  r.full_name as resident_name,
  r.phone     as resident_phone,
  case when r.id is null then 'vacant' else 'occupied' end as occupancy
from public.flats f
left join public.residents r on r.flat_id = f.id and r.status = 'active';

-- ---------- 4. SECURITY (Row Level Security) ----------
-- Only approved portal users can see or change data. Only admins can delete.

alter table public.settings     enable row level security;
alter table public.profiles     enable row level security;
alter table public.flats        enable row level security;
alter table public.residents    enable row level security;
alter table public.charges      enable row level security;
alter table public.payments     enable row level security;
alter table public.invoices     enable row level security;
alter table public.activity_log enable row level security;

do $$
declare t text;
begin
  foreach t in array array['flats','residents','charges','payments','invoices'] loop
    execute format('drop policy if exists "read %1$s"   on public.%1$I', t);
    execute format('drop policy if exists "add %1$s"    on public.%1$I', t);
    execute format('drop policy if exists "edit %1$s"   on public.%1$I', t);
    execute format('drop policy if exists "delete %1$s" on public.%1$I', t);
    execute format('create policy "read %1$s"   on public.%1$I for select to authenticated using (public.is_approved())', t);
    execute format('create policy "add %1$s"    on public.%1$I for insert to authenticated with check (public.is_approved())', t);
    execute format('create policy "edit %1$s"   on public.%1$I for update to authenticated using (public.is_approved()) with check (public.is_approved())', t);
    execute format('create policy "delete %1$s" on public.%1$I for delete to authenticated using (public.is_admin())', t);
  end loop;
end $$;

drop policy if exists "read settings" on public.settings;
drop policy if exists "edit settings" on public.settings;
create policy "read settings" on public.settings for select to authenticated using (public.is_approved());
create policy "edit settings" on public.settings for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "read profiles"   on public.profiles;
drop policy if exists "edit profiles"   on public.profiles;
drop policy if exists "delete profiles" on public.profiles;
create policy "read profiles"   on public.profiles for select to authenticated using (id = auth.uid() or public.is_approved());
create policy "edit profiles"   on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "delete profiles" on public.profiles for delete to authenticated using (public.is_admin());

drop policy if exists "read activity" on public.activity_log;
create policy "read activity" on public.activity_log for select to authenticated using (public.is_admin());

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.generate_monthly_rent(date) to authenticated;
grant execute on function public.is_approved() to authenticated;
grant execute on function public.is_admin() to authenticated;

-- Done! Now go back to the setup guide.
